<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="MimeKit" Version="4.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailSystem.Domain\EmailSystem.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\EdgeSync.ServiceFramework.AspNetCore.Mvc\EdgeSync.ServiceFramework.AspNetCore.Mvc.csproj" />
    <ProjectReference Include="..\..\..\src\EdgeSync.ServiceFramework.Abstractions\EdgeSync.ServiceFramework.Abstractions.csproj" />
    <ProjectReference Include="..\EmailSystem.Application.Contracts\EmailSystem.Application.Contracts.csproj" />
  </ItemGroup>

</Project>