trigger:
- develop

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndTest
  displayName: Build Solution
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9.0 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'd592cbbf-1bf4-4d80-8f88-e70b1ba73d84/bbd4f7fc-436c-4173-aa8a-a1af2e1a3be7'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

- job: createNugetPackage
  displayName: Create Nuget Package
  dependsOn: BuildAndTest
  condition: succeeded()
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9.0 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/src/**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'd592cbbf-1bf4-4d80-8f88-e70b1ba73d84/bbd4f7fc-436c-4173-aa8a-a1af2e1a3be7'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/src/**/*.csproj'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '**/src/**/*.csproj'
      configuration: 'Release'
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      nobuild: true  # 使用現有的構建結果
      versioningScheme: 'off'  # 關閉自動版本設置，使用項目文件中的版本
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'
  - task: DotNetCoreCLI@2
    displayName: dotnet push
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'd592cbbf-1bf4-4d80-8f88-e70b1ba73d84/bbd4f7fc-436c-4173-aa8a-a1af2e1a3be7'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - task: PublishBuildArtifacts@1
    displayName: publish artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nuget-packages'
      publishLocation: 'Container'