<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>1.1.0</Version>
    <Authors>Rain Hu, Kevin Chien</Authors>
    <Company>Advantech</Company>
    
    <Product>EdgeSync ServiceFramework</Product>
    <Copyright>Copyright © Advantech 2025</Copyright>
    <PackageProjectUrl>https://dev.azure.com/Advantech-EBO/IoT%20Platform/_git/edgesync_service_framework</PackageProjectUrl>
    <RepositoryUrl>https://dev.azure.com/Advantech-EBO/IoT%20Platform/_git/edgesync_service_framework</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>