<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>1.0.5</Version>
    <Authors>Rain Hu, Kevin Chien</Authors>
    <Company>Advantech</Company>
    <AbpProjectType>app</AbpProjectType>
  </PropertyGroup>

  <Target Name="SetBuildTimeStamp" BeforeTargets="GenerateAssemblyInfo">
    <PropertyGroup>
      <TimeStamp>$([System.DateTime]::Now.ToString("yyyyMMddHHmmss"))</TimeStamp>
    </PropertyGroup>
  </Target>

  <Target Name="NoWarnOnRazorViewImportedTypeConflicts" BeforeTargets="RazorCoreCompile">
    <PropertyGroup>
      <NoWarn>$(NoWarn);0436</NoWarn>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <Content Remove="$(UserProfile)\.nuget\packages\*\*\contentFiles\any\*\*.abppkg*" />
  </ItemGroup>
</Project>