<Project Sdk="Microsoft.NET.Sdk">

<Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>EdgeSync.ServiceFramework.Core</PackageId>
    <Description>An integrated service handler implementation for NATS</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSource>true</IncludeSource>
    <Nullable>enable</Nullable>
    <RootNamespace>EdgeSync.ServiceFramework</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NATS.NET" Version="2.5.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdgeSync.ServiceFramework.Abstractions\EdgeSync.ServiceFramework.Abstractions.csproj" />
  </ItemGroup>

</Project>
