<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>EdgeSync.ServiceFramework.Testlib</PackageId>
    <Version>1.0.0</Version>
    <Authors>Rain Hu, Kevin Chien</Authors>
    <Company>Advantech</Company>
    <Description>An integrated service handler implementation for NATS</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSource>true</IncludeSource>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdgeSync.ServiceFramework.Abstractions\EdgeSync.ServiceFramework.Abstractions.csproj" />
  </ItemGroup>

</Project>
