<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\EdgeSync.ServiceFramework.Abstractions\EdgeSync.ServiceFramework.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\src\EdgeSync.ServiceFramework.Core\EdgeSync.ServiceFramework.Core.csproj" />
    <ProjectReference Include="..\BookStore.Application\BookStore.Application.csproj" />
  </ItemGroup>

</Project>