<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="NATS.NET" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailSystem.Application.Contracts\EmailSystem.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
