using EdgeSync.ServiceFramework.AspNetCore.Mvc.Abstractions;
using EdgeSync.ServiceFramework.Attributes;

using Microsoft.OpenApi.Models;

using Swashbuckle.AspNetCore.SwaggerGen;

using System.Reflection;

namespace EdgeSync.ServiceFramework.AspNetCore.Mvc.Core.SwaggerGen;

public class AutoGeneratedApiOperationFilter : IOperationFilter
{
    private readonly IAutoConventionRouteBuilder _routeBuilder;

    public AutoGeneratedApiOperationFilter(IAutoConventionRouteBuilder routeBuilder)
    {
        _routeBuilder = routeBuilder;
    }

    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        // Check if this is from our auto-generated controller
        var actionDescriptor = context.ApiDescription.ActionDescriptor;

        if (actionDescriptor.Properties.TryGetValue("ServiceType", out var serviceTypeObj) &&
            actionDescriptor.Properties.TryGetValue("MethodName", out var methodNameObj) &&
            actionDescriptor.Properties.TryGetValue("OriginalMethod", out var originalMethodObj) &&
            serviceTypeObj is Type serviceType &&
            methodNameObj is string &&
            originalMethodObj is MethodInfo originalMethod)
        {
            // Get SubjectAttribute from the original method
            var subjectAttribute = originalMethod.GetCustomAttribute<SubjectAttribute>();

            // Update operation details
            operation.Summary = GenerateSummary(originalMethod.Name);

            var baseDescription = $"**NATS Subject:** `{subjectAttribute?.CustomSubject}`\n\n" +
                                $"This endpoint executes the `{originalMethod.Name}` method from `{serviceType.Name}`.";

            // Try to get XML documentation for the method
            var xmlDocumentation = GetMethodDocumentation(originalMethod);
            if (!string.IsNullOrEmpty(xmlDocumentation))
            {
                operation.Description = $"{baseDescription}\n\n**Method Description:**\n{xmlDocumentation}";
            }
            else
            {
                operation.Description = baseDescription;
            }

            // Set the tag to the cleaned service name
            var serviceName = _routeBuilder.GetServiceName(serviceType.Name);
            operation.Tags = new List<OpenApiTag> { new OpenApiTag { Name = serviceName } };

            // Note: ErrorOr schema unwrapping is handled by ErrorOrSchemaFilter
        }
    }

    private string GenerateSummary(string methodName)
    {
        var normalizedName = methodName.ToLowerInvariant();

        if (normalizedName.Contains("getlist") || normalizedName.Contains("get") && normalizedName.Contains("list"))
            return "Get list of items";
        if (normalizedName.Contains("get") && normalizedName.Contains("count"))
            return "Get count of items";
        if (normalizedName.Contains("get"))
            return "Get item by ID";
        if (normalizedName.Contains("create"))
            return "Create new item";
        if (normalizedName.Contains("update"))
            return "Update existing item";
        if (normalizedName.Contains("delete"))
            return "Delete item";

        return $"Execute {methodName}";
    }

    private string? GetMethodDocumentation(MethodInfo method)
    {
        try
        {
            // Try to get XML documentation from various sources
            var xmlDocPath = GetXmlDocumentationPath(method.DeclaringType?.Assembly);
            if (!string.IsNullOrEmpty(xmlDocPath) && File.Exists(xmlDocPath))
            {
                return ExtractMethodDocumentationFromXml(xmlDocPath, method);
            }

            // Fallback: try to get documentation from method attributes or other sources
            return GetDocumentationFromAttributes(method);
        }
        catch
        {
            // If we can't get documentation, return null
            return null;
        }
    }

    private string? GetXmlDocumentationPath(Assembly? assembly)
    {
        if (assembly == null) return null;

        var xmlFile = $"{assembly.GetName().Name}.xml";
        var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
        
        return File.Exists(xmlPath) ? xmlPath : null;
    }

    private string? ExtractMethodDocumentationFromXml(string xmlPath, MethodInfo method)
    {
        try
        {
            var doc = System.Xml.Linq.XDocument.Load(xmlPath);
            var memberName = GetXmlMemberName(method);
            
            var memberElement = doc.Descendants("member")
                .FirstOrDefault(m => m.Attribute("name")?.Value == memberName);

            var summaryElement = memberElement?.Element("summary");
            if (summaryElement != null)
            {
                return summaryElement.Value.Trim();
            }
        }
        catch
        {
            // Ignore XML parsing errors
        }

        return null;
    }

    private string GetXmlMemberName(MethodInfo method)
    {
        var typeName = method.DeclaringType?.FullName?.Replace('+', '.');
        var methodName = method.Name;
        
        // Handle method parameters for overloaded methods
        var parameters = method.GetParameters();
        if (parameters.Length > 0)
        {
            var paramTypes = parameters.Select(p => p.ParameterType.FullName?.Replace('+', '.'));
            methodName += $"({string.Join(",", paramTypes)})";
        }

        return $"M:{typeName}.{methodName}";
    }

    private string? GetDocumentationFromAttributes(MethodInfo method)
    {
        // Check for common documentation attributes
        var descriptionAttribute = method.GetCustomAttributes()
            .FirstOrDefault(attr => attr.GetType().Name.Contains("Description"));

        if (descriptionAttribute != null)
        {
            var descriptionProperty = descriptionAttribute.GetType().GetProperty("Description");
            return descriptionProperty?.GetValue(descriptionAttribute)?.ToString();
        }

        return null;
    }
}