using EdgeSync.ServiceFramework.Core.SwaggerGen;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi.Models;

using Swashbuckle.AspNetCore.SwaggerGen;

namespace EdgeSync.ServiceFramework.AspNetCore.Mvc.Core.SwaggerGen;

public class DefaultSwaggerGenOptions
{
    public static DefaultSwaggerGenOptions Default { get; private set; } = null!;
    
    private readonly bool _useExceptionHandler;

    public DefaultSwaggerGenOptions(bool useExceptionHandler)
    {
        _useExceptionHandler = useExceptionHandler;
    }

    internal static void SetDefault(bool useExceptionHandler = true)
    {
        Default = new DefaultSwaggerGenOptions(useExceptionHandler);
    }

    public void Configure(SwaggerGenOptions options)
    {
        options.SwaggerDoc("v1", new OpenApiInfo
        {
            Title = "EdgeSync API",
            Version = "v1",
            Description = "Auto-generated API Document for NATS service"
        });

        // Add nats information including subject, service name, method name in swagger description. 
        options.OperationFilter<AutoGeneratedApiOperationFilter>();

        if (_useExceptionHandler)
        {
            // set schema unwrap if enabled useExceptionHandler to match ErrorOrResultFilter
            options.SchemaFilter<ErrorOrSchemaFilter>();
        }

        IncludeXmlComments(options);
    }

    private static void IncludeXmlComments(SwaggerGenOptions options)
    {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        foreach (var assembly in assemblies)
        {
            var xmlFile = $"{assembly.GetName().Name}.xml";
            var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
            if (File.Exists(xmlPath))
            {
                options.IncludeXmlComments(xmlPath);
            }
        }
    }
}