<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>EdgeSync.ServiceFramework.AspNetCore.Mvc</PackageId>
    <Description>An integrated auto-convention implementation for NATS</Description>
    <PackageTags>edgesync;serviceframework;autoconvention;nats;advantech;iot</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSource>true</IncludeSource>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="NATS.NET" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdgeSync.ServiceFramework.Abstractions\EdgeSync.ServiceFramework.Abstractions.csproj" />
  </ItemGroup>

</Project>
