<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>EdgeSync.ServiceFramework.AspNetCore.Mvc</PackageId>
    <Description>An integrated auto-convention implementation for NATS</Description>
    <PackageTags>edgesync;serviceframework;autoconvention;nats;advantech;iot</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSource>true</IncludeSource>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.6" />
    <PackageReference Include="NATS.NET" Version="2.5.12" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdgeSync.ServiceFramework.Abstractions\EdgeSync.ServiceFramework.Abstractions.csproj" />
  </ItemGroup>

</Project>
